import type { TenantConfig } from "@/entities/tenant/model/tenant.types";

export const tenantConfigMap = {
  "cedar-canteen": {
    currency: "EUR",
    description: "Nordic-inspired bowls and comfort food for Cedar Canteen.",
    heroCopy:
      "Cedar Canteen leans into calmer tones, sharper radius, and a more editorial food ordering experience.",
    logoText: "CEDAR / CANTEEN",
    restaurantId: "rest-cedar-canteen",
    slug: "cedar-canteen",
    supportEmail: "hello@cedarcanteen.test",
    tagline: "Scandinavian lunch bar for everyday comfort",
    theme: {
      accent: "#146c57",
      accentForeground: "#f7fff9",
      background: "#eef4ef",
      border: "#bfd3c6",
      card: "#fbfefb",
      cardForeground: "#16211b",
      foreground: "#16211b",
      input: "#ffffff",
      muted: "#dde9e0",
      mutedForeground: "#56655c",
      popover: "#fbfefb",
      popoverForeground: "#16211b",
      primary: "#25493d",
      primaryForeground: "#f6f9f7",
      radius: "1rem",
      ring: "#25493d",
      secondary: "#d5e5d8",
      secondaryForeground: "#203228",
    },
    title: "Cedar Canteen",
  },
  "urban-bites": {
    currency: "USD",
    description: "Bold city comfort food for Urban Bites.",
    heroCopy:
      "Urban Bites uses warmer colors, bolder cards, and a fast mobile-first flow tuned for takeout storefronts.",
    logoText: "URBAN BITES",
    restaurantId: "rest-urban-bites",
    slug: "urban-bites",
    supportEmail: "hello@urbanbites.test",
    tagline: "Fast comfort food for dense city blocks",
    theme: {
      accent: "#13795b",
      accentForeground: "#f5fff9",
      background: "#f6efe4",
      border: "#d9c6b3",
      card: "#fffdf9",
      cardForeground: "#1f1a17",
      foreground: "#1f1a17",
      input: "#fffbf6",
      muted: "#ebdfd2",
      mutedForeground: "#6a594f",
      popover: "#fffdf9",
      popoverForeground: "#1f1a17",
      primary: "#d85a1e",
      primaryForeground: "#fff7f0",
      radius: "1.25rem",
      ring: "#d85a1e",
      secondary: "#efe0cf",
      secondaryForeground: "#3a2418",
    },
    title: "Urban Bites",
  },
} as const satisfies Record<string, TenantConfig>;

export const tenantConfigs = Object.values(tenantConfigMap);
