import type { TenantConfig } from "@/entities/tenant/model/tenant.types";

export const tenantConfigMap = {
  "storeva-mass": {
    allowGuestCheckout: true,
    catalog: {
      categoryCard: "category-classic",
      productCard: "food-classic",
    },
    currency: "RUB",
    description:
      "Storeva — удобный сервис заказа еды на каждый день с акцентом на быстрый выбор, понятные категории, заметные акции и комфортный мобильный сценарий.",
    faviconUrl: "/tenants/storeva-mass/favicon.svg",
    heroCopy:
      "Быстрая доставка любимой еды без лишних шагов: популярные блюда, выгодные комбо и простой путь от выбора до оформления заказа.",
    logoText: "STOREVA",
    logoUrl: "/tenants/storeva-mass/logo.svg",
    restaurantId: "rest-storeva-mass",
    slug: "storeva-mass",
    supportEmail: "hello@storeva.test",
    tagline: "Любимая еда рядом",
    theme: {
      accent: "#248A57",
      accentForeground: "#F5FFF9",
      background: "#FFF8F1",
      border: "#E8D9CB",
      card: "#FFFDF9",
      cardForeground: "#2A211C",
      foreground: "#2A211C",
      input: "#FFFDF9",
      muted: "#F5E8DB",
      mutedForeground: "#7B685C",
      popover: "#FFFDF9",
      popoverForeground: "#2A211C",
      primary: "#F05A28",
      primaryForeground: "#FFF7F2",
      radius: "1.25rem",
      ring: "#F05A28",
      secondary: "#FFE6D6",
      secondaryForeground: "#5B2F1E",
    },
    title: "Storeva",
  },

  "storeva-premium": {
    allowGuestCheckout: true,
    catalog: {
      categoryCard: "category-classic",
      productCard: "food-classic",
    },
    currency: "RUB",
    description:
      "Storeva Food Hall — премиальный сервис заказа еды с акцентом на визуально чистую витрину, качественную подачу блюд и ощущение современного гастрономического бренда.",
    faviconUrl: "/tenants/storeva-premium/favicon.svg",
    heroCopy:
      "Элегантный food delivery experience: спокойная палитра, аккуратные карточки, выразительная гастро-витрина и мягкий путь к заказу любимых блюд.",
    logoText: "STOREVA",
    logoUrl: "/tenants/storeva-premium/logo.svg",
    restaurantId: "rest-storeva-premium",
    slug: "storeva-premium",
    supportEmail: "hello@storeva.test",
    tagline: "Современная еда с красивой подачей",
    theme: {
      accent: "#556B5D",
      accentForeground: "#F6FBF7",
      background: "#FAF4ED",
      border: "#DDCDBF",
      card: "#FFFDFB",
      cardForeground: "#241D18",
      foreground: "#241D18",
      input: "#FFFDFB",
      muted: "#F1E6DA",
      mutedForeground: "#73665C",
      popover: "#FFFDFB",
      popoverForeground: "#241D18",
      primary: "#C96A3D",
      primaryForeground: "#FFF8F4",
      radius: "1.5rem",
      ring: "#C96A3D",
      secondary: "#EAD9CA",
      secondaryForeground: "#4D3427",
    },
    title: "Storeva Food Hall",
  },

  "storeva-street": {
    allowGuestCheckout: true,
    catalog: {
      categoryCard: "category-classic",
      productCard: "food-classic",
    },
    currency: "RUB",
    description:
      "Storeva Street — яркий сервис заказа стритфуда и dark kitchen форматов с акцентом на сочные акценты, быстрый выбор хитов и энергичный мобильный интерфейс.",
    faviconUrl: "/tenants/storeva-street/favicon.svg",
    heroCopy:
      "Смелый и быстрый фуд-опыт: бургеры, роллы, пицца, комбо и новинки — всё, чтобы пользователь выбрал еду за минуты и сразу оформил заказ.",
    logoText: "STOREVA",
    logoUrl: "/tenants/storeva-street/logo.svg",
    restaurantId: "rest-storeva-street",
    slug: "storeva-street",
    supportEmail: "hello@storeva.test",
    tagline: "Яркий вкус. Быстрый заказ.",
    theme: {
      accent: "#1C7C72",
      accentForeground: "#F3FFFC",
      background: "#FFF6EE",
      border: "#E6D2C2",
      card: "#FFFCF8",
      cardForeground: "#211A16",
      foreground: "#211A16",
      input: "#FFFDF9",
      muted: "#F6E5D8",
      mutedForeground: "#7A675B",
      popover: "#FFFCF8",
      popoverForeground: "#211A16",
      primary: "#E64A19",
      primaryForeground: "#FFF7F3",
      radius: "1.25rem",
      ring: "#E64A19",
      secondary: "#FFD9C7",
      secondaryForeground: "#5C2B1C",
    },
    title: "Storeva Street",
  },

  "aiymbrand": {
    allowGuestCheckout: true,
    catalog: {
      categoryCard: "category-fashion",
      productCard: "clothes-fashion",
    },
    currency: "RUB",
    description:
      "Storeva Street — яркий сервис заказа стритфуда и dark kitchen форматов с акцентом на сочные акценты, быстрый выбор хитов и энергичный мобильный интерфейс.",
    faviconUrl: "/tenants/aiymbrand/favicon.svg",
    heroCopy:
      "Смелый и быстрый фуд-опыт: бургеры, роллы, пицца, комбо и новинки — всё, чтобы пользователь выбрал еду за минуты и сразу оформил заказ.",
    logoText: "",
    logoUrl: "/tenants/aiymbrand/logo.png",
    restaurantId: "aiymbrand",
    slug: "aiymbrand",
    supportEmail: "kiranova@bk.ru",
    tagline: "Яркий вкус. Быстрый заказ.",
    theme: {
      accent: "#D5AF5D",
      accentForeground: "#16120A",
      background: "#0F0D0A",
      border: "#2A2418",
      card: "#161310",
      cardForeground: "#F5E7C5",
      foreground: "#F5E7C5",
      input: "#1B1712",
      muted: "#1E1A14",
      mutedForeground: "#B7A57C",
      popover: "#161310",
      popoverForeground: "#F5E7C5",
      primary: "#D5AF5D",
      primaryForeground: "#16120A",
      radius: "1rem",
      ring: "#D5AF5D",
      secondary: "#2A2216",
      secondaryForeground: "#E7D2A0",
    },
    title: "Современное этно",
  },
} as const satisfies Record<string, TenantConfig>;

export const tenantConfigs = Object.values(tenantConfigMap);
