import type { MenuCatalogDto } from "@/features/menu-catalog/api/menu-catalog.types";

const menuCatalogMocks: Record<string, MenuCatalogDto> = {
  "cedar-canteen": {
    categories: [
      {
        description: "Clean bowls with grains, greens, and crisp toppings.",
        id: "cat-bowls",
        name: "Bowls",
        slug: "bowls",
      },
      {
        description: "Comfort classics for colder city evenings.",
        id: "cat-comfort",
        name: "Comfort",
        slug: "comfort",
      },
      {
        description: "Low-intervention desserts and soft bakes.",
        id: "cat-bakery",
        name: "Bakery",
        slug: "bakery",
      },
    ],
    products: [
      {
        category_id: "cat-bowls",
        currency: "EUR",
        description: "Roasted salmon, barley, cucumber ribbons, dill yogurt.",
        id: "prod-nordic-salmon",
        is_available: true,
        name: "Nordic Salmon Bowl",
        price_minor: 1590,
        slug: "nordic-salmon-bowl",
        tags: ["signature", "fresh"],
        visual_hint: "S",
      },
      {
        category_id: "cat-bowls",
        currency: "EUR",
        description: "Crispy halloumi, beet hummus, lentils, herbs.",
        id: "prod-halloumi-lentil",
        is_available: true,
        name: "Halloumi Lentil Bowl",
        price_minor: 1390,
        slug: "halloumi-lentil-bowl",
        tags: ["vegetarian", "protein"],
        visual_hint: "H",
      },
      {
        category_id: "cat-comfort",
        currency: "EUR",
        description: "Braised beef, mashed potatoes, pickled onion.",
        id: "prod-beef-plate",
        is_available: true,
        name: "Braised Beef Plate",
        price_minor: 1740,
        slug: "braised-beef-plate",
        tags: ["comfort", "slow-cooked"],
        visual_hint: "B",
      },
      {
        category_id: "cat-bakery",
        currency: "EUR",
        description: "Cardamom bun with vanilla glaze.",
        id: "prod-cardamom-bun",
        is_available: false,
        name: "Cardamom Bun",
        price_minor: 590,
        slug: "cardamom-bun",
        tags: ["bakery", "sweet"],
        visual_hint: "C",
      },
    ],
    restaurant: {
      city: "Helsinki",
      currency: "EUR",
      delivery_eta_minutes: 28,
      id: "rest-cedar-canteen",
      kitchen_note: "Fresh bowls in under 30 minutes.",
      min_order_amount_minor: 1800,
      name: "Cedar Canteen Kitchen",
      tenant_slug: "cedar-canteen",
    },
  },
  "urban-bites": {
    categories: [
      {
        description: "Fast comfort food with bold flavor and easy sharing.",
        id: "cat-burgers",
        name: "Burgers",
        slug: "burgers",
      },
      {
        description: "Street-style sides and loaded comfort bowls.",
        id: "cat-sides",
        name: "Sides",
        slug: "sides",
      },
      {
        description: "Refreshing drinks for dense lunch rushes.",
        id: "cat-drinks",
        name: "Drinks",
        slug: "drinks",
      },
    ],
    products: [
      {
        category_id: "cat-burgers",
        currency: "USD",
        description: "Double smashed patties, cheddar, pickles, city sauce.",
        id: "prod-city-smash",
        is_available: true,
        name: "City Smash Burger",
        price_minor: 1490,
        slug: "city-smash-burger",
        tags: ["best seller", "fast"],
        visual_hint: "C",
      },
      {
        category_id: "cat-burgers",
        currency: "USD",
        description: "Hot honey chicken, slaw, butter bun.",
        id: "prod-hot-honey",
        is_available: true,
        name: "Hot Honey Chicken",
        price_minor: 1360,
        slug: "hot-honey-chicken",
        tags: ["spicy", "signature"],
        visual_hint: "H",
      },
      {
        category_id: "cat-sides",
        currency: "USD",
        description: "Crispy fries, smoked aioli, citrus salt.",
        id: "prod-loaded-fries",
        is_available: true,
        name: "Loaded Citrus Fries",
        price_minor: 690,
        slug: "loaded-citrus-fries",
        tags: ["shareable", "crispy"],
        visual_hint: "F",
      },
      {
        category_id: "cat-drinks",
        currency: "USD",
        description: "Sparkling yuzu lemonade with mint.",
        id: "prod-yuzu-fizz",
        is_available: true,
        name: "Yuzu Mint Fizz",
        price_minor: 540,
        slug: "yuzu-mint-fizz",
        tags: ["drink", "refreshing"],
        visual_hint: "Y",
      },
    ],
    restaurant: {
      city: "Brooklyn",
      currency: "USD",
      delivery_eta_minutes: 22,
      id: "rest-urban-bites",
      kitchen_note: "Takeout tuned for busy lunch peaks.",
      min_order_amount_minor: 1500,
      name: "Urban Bites Kitchen",
      tenant_slug: "urban-bites",
    },
  },
};

export function createMockMenuCatalogDto(tenantSlug: string): MenuCatalogDto {
  return menuCatalogMocks[tenantSlug] ?? menuCatalogMocks["urban-bites"];
}
